on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Mostrar contenido del directorio
        run: ls -la

      - name: Hello world action step
        id: hello
        uses: ./ # Usa la acción local desde el mismo repo
        with:
          who-to-greet: 'Luis Fernando'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
